version: "3"

services:

##################################################################
  ############################# Canton #############################
##################################################################
 
  cantonB:
    image: digitalasset/canton-community:latest
    tty: true
    volumes:
      - ./canton:/canton/app
      - ./daml:/canton/daml
    environment:
      - DOMAIN_URL=${CANTON_DOMAIN_URL}
      - LEDGER_PORT=${LEDGER_PORT_B}
    ports:
      - ${LEDGER_PORT_B}:${LEDGER_PORT_B}
    command: --config /canton/app/canton_2.conf --bootstrap /canton/app/init_2.canton

##################################################################
  ########################### Navigator ############################
##################################################################

  navigatorB:
    image: digitalasset/daml-sdk:1.18.0
    working_dir: /data
    ports:
      - ${NAVIGATOR_PORT_B}:${NAVIGATOR_PORT_B}
    volumes:
      - ./daml:/data
    command: daml ledger navigator --host cantonB --port ${LEDGER_PORT_B} --port ${NAVIGATOR_PORT_B}
    depends_on:
      - cantonB
    links:
      - cantonB

##################################################################
  ############################ JsonApi #############################
##################################################################

  jsonApiB:
    image: digitalasset/daml-sdk:1.18.0
    working_dir: /data
    ports:
      - ${JSON_API_PORT_B}:${JSON_API_PORT_B}
    volumes:
      - ./daml:/data
    command: daml json-api --ledger-host cantonB --ledger-port ${LEDGER_PORT_B} --http-port ${JSON_API_PORT_B} --address 0.0.0.0 --allow-insecure-tokens
    depends_on:
      - cantonB
    links:
      - cantonB

##################################################################
  ############################# React ##############################
##################################################################

  reactB:
    image: node:alpine
    working_dir: /usr/src/app
    environment:
      - JSON_API_URL=${JSON_API_URL_A} 
    ports:
      - ${REACT_PORT_B}:3000
    volumes:
     - ./ui:/usr/src/app
    command: sh -c "yarn install && yarn start"
    links:
      - jsonApiB

##################################################################
  ########################### Wordpress ############################
##################################################################

  nginxB:
    image: nginx:alpine
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx_b.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT_B}:80
    depends_on:
      - wordpressB
      - jsonApiB
    links:
      - wordpressB
      - jsonApiB

  wordpressB:
    image: wordpress:php7.4-fpm-alpine
    environment:
     - WORDPRESS_DB_HOST=mysqlB
     - WORDPRESS_DB_NAME=wordpress
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_PASSWORD=password
    volumes:
     - ./wordpress:/var/www/html
    depends_on:
      - mysqlB
    links:
      - mysqlB

  mysqlB:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./data/mysqlB:/var/lib/mysql
