version: "3"

services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - wordpress
      - daml_json_api
    links:
      - wordpress
      - daml_json_api

  canton:
    image: digitalasset/canton-community:latest
    #hostname: canton
    #entrypoint: []
    tty: true
    volumes:
      - ./canton:/canton/app
      - ./daml:/canton/daml
    ports:
      - ${LEDGER_PORT}:${LEDGER_PORT}
      - 12021:12021
    command: --config /canton/app/canton.conf --bootstrap /canton/app/init.canton

  daml_json_api:
    image: digitalasset/daml-sdk:1.18.0
    working_dir: /data
    ports:
      - ${JSON_API_PORT}:${JSON_API_PORT}
    volumes:
      - ./daml:/data
    command: daml json-api --ledger-port ${LEDGER_PORT} --http-port ${JSON_API_PORT} --address 0.0.0.0 --ledger-host ${LEDGER_HOST} --allow-insecure-tokens

  ui:
    image: node:alpine
    working_dir: /usr/src/app
    environment:
      - LEDGER_ID=${LEDGER_ID}
      - JSON_API_URL=${JSON_API_URL} 
    ports:
      - 3000:3000
    volumes:
     - ./ui:/usr/src/app
    command: sh -c "yarn install && yarn start"

  wordpress:
    image: wordpress:php7.4-fpm-alpine
    environment:
     - WORDPRESS_DB_NAME=wordpress
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_PASSWORD=password
    volumes:
     - ./wordpress:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./data/mysql:/var/lib/mysql
